import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ComparisonTable, Citation } from '@/types';

// OutSail brand palette (see docs/design-system.md) — blue + neutral only.
const HARBOR: [number, number, number] = [30, 58, 107]; // #1E3A6B
const OSBLUE: [number, number, number] = [66, 119, 199]; // #4277C7
const DEEP_NAVY: [number, number, number] = [15, 23, 42]; // #0F172A
const SLATE: [number, number, number] = [51, 65, 85]; // #334155
const COOL_GRAY: [number, number, number] = [100, 116, 139]; // #64748B
const OFF_WHITE: [number, number, number] = [244, 247, 251]; // #F4F7FB
const WHITE: [number, number, number] = [255, 255, 255];

export function generatePdfBuffer(
  comparisonData: ComparisonTable,
  standardizationNotes: string[],
  vendorNotes: Record<string, string[]>,
  nextSteps: string[],
  citations: Citation[],
  projectName: string
): Buffer {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  // Header — two-tone OutSail wordmark (Deep Harbor "Out" + OutSail Blue "Sail")
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...HARBOR);
  doc.text('Out', 14, 15);
  const outWidth = doc.getTextWidth('Out');
  doc.setTextColor(...OSBLUE);
  doc.text('Sail', 14 + outWidth, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(...DEEP_NAVY);
  doc.text(`Proposal Comparison — ${projectName}`, 14, 24);
  doc.setFontSize(8);
  doc.setTextColor(...COOL_GRAY);
  doc.text(`Generated ${new Date().toLocaleDateString()}`, 14, 30);

  let yPos = 36;

  for (const section of comparisonData.sections) {
    // Stay in the brand's single blue family: Deep Harbor banners, OutSail Blue
    // for Totals to set it apart. No greens/teals/purples/ambers.
    const bgColor: [number, number, number] = section.name === 'Totals' ? OSBLUE : HARBOR;

    const headers = ['Category', ...comparisonData.vendors];
    const body = section.rows.map((row) => [
      row.label,
      ...row.values.map((v) => v.display),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [[{ content: section.name, colSpan: headers.length, styles: { fillColor: bgColor, textColor: WHITE, fontStyle: 'bold', fontSize: 9 } }], headers],
      body,
      theme: 'grid',
      styles: { fontSize: 7, cellPadding: 2, textColor: SLATE },
      headStyles: { fillColor: OFF_WHITE, textColor: HARBOR, fontStyle: 'bold', fontSize: 7 },
      columnStyles: { 0: { cellWidth: 55 } },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

    if (yPos > 180) {
      doc.addPage();
      yPos = 14;
    }
  }

  // Notes page
  doc.addPage();
  yPos = 14;

  doc.setFontSize(12);
  doc.setTextColor(...DEEP_NAVY);
  doc.text('Standardization Notes', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(...SLATE);
  for (const note of standardizationNotes) {
    const lines = doc.splitTextToSize(`• ${note}`, 260);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 4 + 2;
    if (yPos > 190) {
      doc.addPage();
      yPos = 14;
    }
  }

  yPos += 6;
  doc.setFontSize(12);
  doc.setTextColor(...DEEP_NAVY);
  doc.text('Vendor Notes', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(...SLATE);
  for (const [vendor, notes] of Object.entries(vendorNotes)) {
    doc.setFontSize(9);
    doc.setTextColor(...DEEP_NAVY);
    doc.text(vendor, 14, yPos);
    yPos += 4;
    doc.setFontSize(8);
    doc.setTextColor(...SLATE);
    for (const note of notes) {
      const lines = doc.splitTextToSize(`• ${note}`, 260);
      doc.text(lines, 18, yPos);
      yPos += lines.length * 4 + 2;
      if (yPos > 190) {
        doc.addPage();
        yPos = 14;
      }
    }
    yPos += 2;
  }

  yPos += 6;
  doc.setFontSize(12);
  doc.setTextColor(...DEEP_NAVY);
  doc.text('Next Steps', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(...SLATE);
  for (const step of nextSteps) {
    const lines = doc.splitTextToSize(`• ${step}`, 260);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 4 + 2;
    if (yPos > 190) {
      doc.addPage();
      yPos = 14;
    }
  }

  // Footer on each page
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...COOL_GRAY);
    doc.text('Generated by OutSail | Confidential', 14, 200);
    doc.text(`Page ${i} of ${pageCount}`, 270, 200);
  }

  const arrayBuf = doc.output('arraybuffer');
  return Buffer.from(arrayBuf);
}
