import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ComparisonTable, Citation } from '@/types';

export function generatePdfBuffer(
  comparisonData: ComparisonTable,
  standardizationNotes: string[],
  vendorNotes: Record<string, string[]>,
  nextSteps: string[],
  citations: Citation[],
  projectName: string
): Buffer {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  // Header
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138); // blue-900
  doc.text('OutSail', 14, 15);
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text(`Proposal Comparison — ${projectName}`, 14, 24);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated ${new Date().toLocaleDateString()}`, 14, 30);

  let yPos = 36;

  // Comparison table per section
  const sectionColors: Record<string, [number, number, number]> = {
    'Software Fees (Recurring)': [37, 99, 235],
    'Implementation Fees (One-Time)': [5, 150, 105],
    'Service Fees (Recurring)': [147, 51, 234],
    Discounts: [217, 119, 6],
    Totals: [30, 41, 59],
  };

  for (const section of comparisonData.sections) {
    const bgColor = sectionColors[section.name] || [71, 85, 105];

    const headers = ['Category', ...comparisonData.vendors];
    const body = section.rows.map((row) => [
      row.label,
      ...row.values.map((v) => v.display),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [[{ content: section.name, colSpan: headers.length, styles: { fillColor: bgColor, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 } }], headers],
      body,
      theme: 'grid',
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: 'bold', fontSize: 7 },
      columnStyles: { 0: { cellWidth: 55 } },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

    if (yPos > 180) {
      doc.addPage();
      yPos = 14;
    }
  }

  // Notes page
  doc.addPage();
  yPos = 14;

  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Standardization Notes', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  for (const note of standardizationNotes) {
    const lines = doc.splitTextToSize(`• ${note}`, 260);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 4 + 2;
    if (yPos > 190) {
      doc.addPage();
      yPos = 14;
    }
  }

  yPos += 6;
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Vendor Notes', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  for (const [vendor, notes] of Object.entries(vendorNotes)) {
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(vendor, 14, yPos);
    yPos += 4;
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    for (const note of notes) {
      const lines = doc.splitTextToSize(`• ${note}`, 260);
      doc.text(lines, 18, yPos);
      yPos += lines.length * 4 + 2;
      if (yPos > 190) {
        doc.addPage();
        yPos = 14;
      }
    }
    yPos += 2;
  }

  yPos += 6;
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Next Steps', 14, yPos);
  yPos += 6;
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  for (const step of nextSteps) {
    const lines = doc.splitTextToSize(`• ${step}`, 260);
    doc.text(lines, 14, yPos);
    yPos += lines.length * 4 + 2;
    if (yPos > 190) {
      doc.addPage();
      yPos = 14;
    }
  }

  // Footer on each page
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by OutSail | Confidential', 14, 200);
    doc.text(`Page ${i} of ${pageCount}`, 270, 200);
  }

  const arrayBuf = doc.output('arraybuffer');
  return Buffer.from(arrayBuf);
}
